[tool.rye]
virtual = true
dev-dependencies = [
    "click>=8.1.7",
    "torch==2.3.1+cpu",
    "torchvision==0.18.1+cpu",
    "setuptools>=69.5.1",
]

[[tool.rye.sources]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
